wallpaper {
	monitor = # default setting
    # Please note: Hyprpaper gracefully handles a missing file path
	path = ~/Pictures/Wallpapers/nix-wallpaper-nineish-solarized-dark.png
	fit_mode = cover
}
