/*
Please Note:

This hardware configuration IS manually edited after labelling the disk partitions and verifying the disk labels manually.

For compatibility with your hardware device, use nixos-generate-config command to generate hardware configuration based on your device architecture. You may use the (Bash) command: 
$ nixos-generate-config --root /mnt
This detects your mounted partitions and writes the correct config automatically.

However, it is highly recommended to partition and label your disk partitions likewise, as done here.

You will need to create three disk partitions, viz., `root`, `boot` and `swap` partitions during NixOS installation. Thenafter, verify your partitioned disk and the concerned disk partitions using lsblk command.

Now let's suppose the concerned disk is /dev/sdX, with boot partition as /dev/sdX1, swap partition as /dev/sdX2 and root partition as /dev/sdX3.

You can consequently use the following commands in your (Bash) shell:
- For ext4 root:
    $ e2label /dev/sdX3 nixos-root
- For FAT32 boot:
    $ fatlabel /dev/sdX1 nixos-boot
- For labelling the [SWAP] partition:
    $ swaplabel -L nixos-swap /dev/sdX2

Thenafter, verify using the following command: 
$ lsblk -f | grep -E "root|boot|swap"
*/

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "ehci_pci"  # USB 3 and USB 2 host controllers
    "thunderbolt"
    "ahci"  # SATA -- essential on older machines without NVMe
    "nvme"
    "usb_storage"  # The drive itself, booted over USB
    "uas"  # USB attached SCSI (faster USB 3 storage protocol
    "sd_mod"
    "sdhci_pci"
    "virtio_pci"  # VMs/QEMU -- useful if ever testing in a VM
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos-root";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/nixos-boot";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-label/nixos-swap"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
